### ISSUE TITLE
Update Drop expand/collapse styling

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/drop#15]
``` scss
/**
 * Styling for expand/collapse icons
 */
.dropdown-basic > a .dropdown-show,
.dropdown-basic > a .dropdown-hide,
.js-drop .dropdown-basic > a.active .dropdown-show {
    display: none;
    visibility: hidden;
}

.js-drop .dropdown-basic > a .dropdown-show,
.js-drop .dropdown-basic > a.active .dropdown-hide {
    display: inline-block;
    visibility: visible;
}
```
